/**
 * Supabase Storage helper — EU (Frankfurt) data residency for candidate documents.
 *
 * Server-side only: uses the SERVICE_ROLE key, which bypasses RLS. NEVER expose
 * this key to the frontend. Files live in a PRIVATE bucket; access is granted via
 * short-lived signed URLs generated by the API after token verification.
 */
import { createClient, SupabaseClient } from '@supabase/supabase-js'

export const DOCUMENTS_BUCKET = 'candidate-documents'

let client: SupabaseClient | null = null

export function getStorage(): SupabaseClient | null {
  if (client) return client
  const url = process.env.SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_KEY
  if (!url || !key) return null // not configured yet → caller falls back / errors clearly
  client = createClient(url, key, { auth: { persistSession: false } })
  return client
}

export function storageConfigured(): boolean {
  return !!(process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_KEY)
}
